language: go
dist: bionic
go:
- '1.16.x'
- '1.17.x'
addons:
  apt:
    packages:
      - python3 
      - python3-pip 
      - python3-setuptools

env:
  global:
    - GO111MODULE="off"

before_install:
  - sudo apt-get update && sudo apt-get upgrade -y openssl

install:
  # Required to install detect-secrets
  - sudo chmod o+rwx /usr/lib/python3/dist-packages/
  - python3 -m pip install -U pip
  - pip3 install --upgrade "git+https://github.com/ibm/detect-secrets.git@master#egg=detect-secrets"
  - go get -u github.com/kardianos/govendor

before_script:
  - bin/detect_secrets.sh
  - govendor sync

script:
  - go test $(go list ./... | grep -v "plugin_examples" | grep -v "vendor")
