// Code generated by go-bindata. DO NOT EDIT.
// sources:
// i18n/resources/all.de_DE.json (2.787kB)
// i18n/resources/all.en_US.json (2.588kB)
// i18n/resources/all.es_ES.json (2.683kB)
// i18n/resources/all.fr_FR.json (2.627kB)
// i18n/resources/all.it_IT.json (2.684kB)
// i18n/resources/all.ja_JP.json (2.849kB)
// i18n/resources/all.ko_KR.json (2.764kB)
// i18n/resources/all.pt_BR.json (2.634kB)
// i18n/resources/all.zh_Hans.json (2.591kB)
// i18n/resources/all.zh_Hant.json (2.572kB)

package resources

import (
	"crypto/sha256"
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _i18nResourcesAllDe_deJson = []byte(`[
  {
    "id": "\nEnter a number",
    "translation": "\nGeben Sie eine Zahl ein."
  },
  {
    "id": "An error occurred when creating log file '{{.Path}}':\n{{.Error}}\n\n",
    "translation": "Beim Erstellen der Protokolldatei '{{.Path}}' ist ein Fehler aufgetreten:\n{{.Error}}\n\n"
  },
  {
    "id": "An error occurred while dumping request:\n{{.Error}}\n",
    "translation": "Bei der Anforderung zum Erstellen eines Speicherauszugs ist ein Fehler aufgetreten:\n{{.Error}}\n"
  },
  {
    "id": "An error occurred while dumping response:\n{{.Error}}\n",
    "translation": "Bei der Antwort bezüglich der Erstellung eines Speicherauszugs ist ein Fehler aufgetreten:\n{{.Error}}\n"
  },
  {
    "id": "Could not read from input: ",
    "translation": "Could not read from input: "
  },
  {
    "id": "Elapsed:",
    "translation": "Verstrichen:"
  },
  {
    "id": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}"
  },
  {
    "id": "FAILED",
    "translation": "FEHLGESCHLAGEN"
  },
  {
    "id": "Failed, header could not convert to csv format",
    "translation": "Failed, header could not convert to csv format"
  },
  {
    "id": "Failed, rows could not convert to csv format",
    "translation": "Failed, rows could not convert to csv format"
  },
  {
    "id": "Invalid grant type: ",
    "translation": "Invalid grant type: "
  },
  {
    "id": "Invalid token: ",
    "translation": "Ungültiges Token: "
  },
  {
    "id": "OK",
    "translation": "OK"
  },
  {
    "id": "Please enter 'y', 'n', 'yes' or 'no'.",
    "translation": "Geben Sie 'j', 'n', 'ja' oder 'nein' ein."
  },
  {
    "id": "Please enter a number between 1 to {{.Count}}.",
    "translation": "Geben Sie eine Zahl zwischen 1 und {{.Count}} ein."
  },
  {
    "id": "Please enter a valid floating number.",
    "translation": "Geben Sie eine gültige Gleitkommazahl ein."
  },
  {
    "id": "Please enter a valid number.",
    "translation": "Geben Sie eine gültige Zahl ein."
  },
  {
    "id": "Please enter value.",
    "translation": "Geben Sie einen Wert ein."
  },
  {
    "id": "REQUEST:",
    "translation": "ANFORDERUNG:"
  },
  {
    "id": "RESPONSE:",
    "translation": "ANTWORT:"
  },
  {
    "id": "Remote server error. Status code: {{.StatusCode}}, error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "Fehler auf dem fernen Server. Statuscode: {{.StatusCode}}, Fehlercode: {{.ErrorCode}}, Nachricht: {{.Message}}"
  },
  {
    "id": "Unable to save plugin config: ",
    "translation": "Speichern der Plug-in-Konfiguration nicht möglich: "
  },
  {
    "id": "Session inactive: ",
    "translation": "Session inactive: "
  }
]
`)

func i18nResourcesAllDe_deJsonBytes() ([]byte, error) {
	return _i18nResourcesAllDe_deJson, nil
}

func i18nResourcesAllDe_deJson() (*asset, error) {
	bytes, err := i18nResourcesAllDe_deJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "i18n/resources/all.de_DE.json", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xda, 0xf1, 0x1f, 0x67, 0x68, 0x69, 0xc7, 0xf7, 0xc3, 0xa4, 0xe1, 0xc1, 0xb4, 0x7e, 0x4f, 0x90, 0xba, 0x9c, 0x2d, 0xf5, 0x86, 0x94, 0x1f, 0xec, 0xf2, 0xf3, 0x50, 0x6d, 0xa, 0x5e, 0xba, 0xf8}}
	return a, nil
}

var _i18nResourcesAllEn_usJson = []byte(`[
  {
    "id": "\nEnter a number",
    "translation": "\nEnter a number"
  },
  {
    "id": "An error occurred when creating log file '{{.Path}}':\n{{.Error}}\n\n",
    "translation": "An error occurred when creating log file '{{.Path}}':\n{{.Error}}\n\n"
  },
  {
    "id": "An error occurred while dumping request:\n{{.Error}}\n",
    "translation": "An error occurred while dumping request:\n{{.Error}}\n"
  },
  {
    "id": "An error occurred while dumping response:\n{{.Error}}\n",
    "translation": "An error occurred while dumping response:\n{{.Error}}\n"
  },
  {
    "id": "Could not read from input: ",
    "translation": "Could not read from input: "
  },
  {
    "id": "Elapsed:",
    "translation": "Elapsed:"
  },
  {
    "id": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}"
  },
  {
    "id": "FAILED",
    "translation": "FAILED"
  },
  {
    "id": "Failed, header could not convert to csv format",
    "translation": "Failed, header could not convert to csv format"
  },
  {
    "id": "Failed, rows could not convert to csv format",
    "translation": "Failed, rows could not convert to csv format"
  },
  {
    "id": "Invalid grant type: ",
    "translation": "Invalid grant type: "
  },
  {
    "id": "Invalid token: ",
    "translation": "Invalid token: "
  },
  {
    "id": "OK",
    "translation": "OK"
  },
  {
    "id": "Please enter 'y', 'n', 'yes' or 'no'.",
    "translation": "Please enter 'y', 'n', 'yes' or 'no'."
  },
  {
    "id": "Please enter a number between 1 to {{.Count}}.",
    "translation": "Please enter a number between 1 to {{.Count}}."
  },
  {
    "id": "Please enter a valid floating number.",
    "translation": "Please enter a valid floating number."
  },
  {
    "id": "Please enter a valid number.",
    "translation": "Please enter a valid number."
  },
  {
    "id": "Please enter value.",
    "translation": "Please enter value."
  },
  {
    "id": "REQUEST:",
    "translation": "REQUEST:"
  },
  {
    "id": "RESPONSE:",
    "translation": "RESPONSE:"
  },
  {
    "id": "Remote server error. Status code: {{.StatusCode}}, error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "Remote server error. Status code: {{.StatusCode}}, error code: {{.ErrorCode}}, message: {{.Message}}"
  },
  {
    "id": "Unable to save plugin config: ",
    "translation": "Unable to save plugin config: "
  },
  {
    "id": "Session inactive: ",
    "translation": "Session inactive: "
  }
]
`)

func i18nResourcesAllEn_usJsonBytes() ([]byte, error) {
	return _i18nResourcesAllEn_usJson, nil
}

func i18nResourcesAllEn_usJson() (*asset, error) {
	bytes, err := i18nResourcesAllEn_usJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "i18n/resources/all.en_US.json", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xe9, 0x57, 0x32, 0xa, 0x51, 0xba, 0xa9, 0xe, 0x7c, 0x73, 0x3e, 0x7b, 0x98, 0xb6, 0x61, 0xab, 0x71, 0x9, 0x48, 0xcc, 0x5, 0x34, 0x6f, 0x9e, 0x6d, 0x3f, 0x55, 0x32, 0x18, 0x3c, 0xcb, 0x4b}}
	return a, nil
}

var _i18nResourcesAllEs_esJson = []byte(`[ {
    "id": "\nEnter a number",
    "translation": "\nEscriba un número"
  },
  {
    "id": "An error occurred when creating log file '{{.Path}}':\n{{.Error}}\n\n",
    "translation": "Se ha producido un error al crear el archivo de registro '{{.Path}}':\n{{.Error}}\n\n"
  },
  {
    "id": "An error occurred while dumping request:\n{{.Error}}\n",
    "translation": "Se ha producido un error al volcar la solicitud:\n{{.Error}}\n"
  },
  {
    "id": "An error occurred while dumping response:\n{{.Error}}\n",
    "translation": "Se ha producido un error al volcar la respuesta:\n{{.Error}}\n"
  },
  {
    "id": "Could not read from input: ",
    "translation": "Could not read from input: "
  },
  {
    "id": "Elapsed:",
    "translation": "Transcurrido:"
  },
  {
    "id": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}"
  },
  {
    "id": "FAILED",
    "translation": "ERROR"
  },
  {
    "id": "Failed, header could not convert to csv format",
    "translation": "Failed, header could not convert to csv format"
  },
  {
    "id": "Failed, rows could not convert to csv format",
    "translation": "Failed, rows could not convert to csv format"
  },
  {
    "id": "Invalid grant type: ",
    "translation": "Invalid grant type: "
  },
  {
    "id": "Invalid token: ",
    "translation": "Señal no válida: "
  },
  {
    "id": "OK",
    "translation": "Correcto"
  },
  {
    "id": "Please enter 'y', 'n', 'yes' or 'no'.",
    "translation": "Especifique 'y', 'n', 'yes' o 'no'."
  },
  {
    "id": "Please enter a number between 1 to {{.Count}}.",
    "translation": "Especifique un número entre 1 y {{.Count}}."
  },
  {
    "id": "Please enter a valid floating number.",
    "translation": "Especifique un número flotante válido."
  },
  {
    "id": "Please enter a valid number.",
    "translation": "Especifique un número válido."
  },
  {
    "id": "Please enter value.",
    "translation": "Especifique un valor."
  },
  {
    "id": "REQUEST:",
    "translation": "SOLICITUD:"
  },
  {
    "id": "RESPONSE:",
    "translation": "RESPUESTA:"
  },
  {
    "id": "Remote server error. Status code: {{.StatusCode}}, error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "Error del servidor remoto. Código de estado: {{.StatusCode}}, código de error: {{.ErrorCode}}, mensaje: {{.Message}}"
  },
  {
    "id": "Unable to save plugin config: ",
    "translation": "No se ha podido guardar la configuración del plugin:"
  },
  {
    "id": "Session inactive: ",
    "translation": "Session inactive: "
  }
]
`)

func i18nResourcesAllEs_esJsonBytes() ([]byte, error) {
	return _i18nResourcesAllEs_esJson, nil
}

func i18nResourcesAllEs_esJson() (*asset, error) {
	bytes, err := i18nResourcesAllEs_esJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "i18n/resources/all.es_ES.json", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xa1, 0xea, 0xc8, 0x71, 0xda, 0xa, 0x98, 0xe1, 0x1a, 0x54, 0xa8, 0x8, 0xf0, 0xab, 0xaa, 0x2, 0x69, 0xfd, 0x66, 0x95, 0x6, 0xf8, 0x9, 0xf1, 0xf4, 0x21, 0xe4, 0x5, 0xf8, 0xc, 0x2b, 0x2e}}
	return a, nil
}

var _i18nResourcesAllFr_frJson = []byte(`[
  {
    "id": "\nEnter a number",
    "translation": "\nEntrez un nombre"
  },
  {
    "id": "An error occurred when creating log file '{{.Path}}':\n{{.Error}}\n\n",
    "translation": "Erreur lors de la création du fichier journal '{{.Path}}':\n{{.Error}}\n\n"
  },
  {
    "id": "An error occurred while dumping request:\n{{.Error}}\n",
    "translation": "Erreur lors de la demande de vidage :\n{{.Error}}\n"
  },
  {
    "id": "An error occurred while dumping response:\n{{.Error}}\n",
    "translation": "Erreur lors de la réponse de vidage :\n{{.Error}}\n"
  },
  {
    "id": "Could not read from input: ",
    "translation": "Could not read from input: "
  },
  {
    "id": "Elapsed:",
    "translation": "Ecoulé :"
  },
  {
    "id": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}"
  },
  {
    "id": "FAILED",
    "translation": "ECHEC"
  },
  {
    "id": "Failed, header could not convert to csv format",
    "translation": "Failed, header could not convert to csv format"
  },
  {
    "id": "Failed, rows could not convert to csv format",
    "translation": "Failed, rows could not convert to csv format"
  },
  {
    "id": "Invalid grant type: ",
    "translation": "Invalid grant type: "
  },
  {
    "id": "Invalid token: ",
    "translation": "Jeton non valide : "
  },
  {
    "id": "OK",
    "translation": "OK"
  },
  {
    "id": "Please enter 'y', 'n', 'yes' or 'no'.",
    "translation": "L'entrée doit être 'y', 'n', 'yes' ou 'no'."
  },
  {
    "id": "Please enter a number between 1 to {{.Count}}.",
    "translation": "Entrez un nombre entre 1 et {{.Count}}."
  },
  {
    "id": "Please enter a valid floating number.",
    "translation": "Entrez un nombre flottant valide."
  },
  {
    "id": "Please enter a valid number.",
    "translation": "Entrez un nombre valide."
  },
  {
    "id": "Please enter value.",
    "translation": "Entrez une valeur."
  },
  {
    "id": "REQUEST:",
    "translation": "DEMANDE :"
  },
  {
    "id": "RESPONSE:",
    "translation": "REPONSE :"
  },
  {
    "id": "Remote server error. Status code: {{.StatusCode}}, error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "Erreur du serveur distant. Code de statut : {{.StatusCode}}, code d'erreur : {{.ErrorCode}}, message : {{.Message}}"
  },
  {
    "id": "Unable to save plugin config: ",
    "translation": "Impossible d'enregistrer la configuration du plug-in : "
  },
  {
    "id": "Session inactive: ",
    "translation": "Session inactive: "
  }
]
`)

func i18nResourcesAllFr_frJsonBytes() ([]byte, error) {
	return _i18nResourcesAllFr_frJson, nil
}

func i18nResourcesAllFr_frJson() (*asset, error) {
	bytes, err := i18nResourcesAllFr_frJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "i18n/resources/all.fr_FR.json", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xa6, 0x25, 0x4a, 0x4f, 0xcd, 0x23, 0x22, 0xee, 0xb8, 0x5, 0xdf, 0xfc, 0xd1, 0x91, 0x1d, 0xc1, 0x32, 0xe1, 0x81, 0x9a, 0x59, 0x1e, 0x3d, 0xc0, 0xf9, 0xe8, 0x37, 0x97, 0xcb, 0x9f, 0xed, 0x2d}}
	return a, nil
}

var _i18nResourcesAllIt_itJson = []byte(`[
  {
    "id": "\nEnter a number",
    "translation": "\nImmetti un numero"
  },
  {
    "id": "An error occurred when creating log file '{{.Path}}':\n{{.Error}}\n\n",
    "translation": "Si è verificato un errore durante la creazione del file di log '{{.Path}}':\n{{.Error}}\n\n"
  },
  {
    "id": "An error occurred while dumping request:\n{{.Error}}\n",
    "translation": "Si è verificato un errore durante il dump della richiesta:\n{{.Error}}\n"
  },
  {
    "id": "An error occurred while dumping response:\n{{.Error}}\n",
    "translation": "Si è verificato un errore durante il dump della risposta:\n{{.Error}}\n"
  },
  {
    "id": "Could not read from input: ",
    "translation": "Could not read from input: "
  },
  {
    "id": "Elapsed:",
    "translation": "Trascorso:"
  },
  {
    "id": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}"
  },
  {
    "id": "FAILED",
    "translation": "NON RIUSCITO"
  },
  {
    "id": "Failed, header could not convert to csv format",
    "translation": "Failed, header could not convert to csv format"
  },
  {
    "id": "Failed, rows could not convert to csv format",
    "translation": "Failed, rows could not convert to csv format"
  },
  {
    "id": "Invalid grant type: ",
    "translation": "Invalid grant type: "
  },
  {
    "id": "Invalid token: ",
    "translation": "Token non valido: "
  },
  {
    "id": "OK",
    "translation": "OK"
  },
  {
    "id": "Please enter 'y', 'n', 'yes' or 'no'.",
    "translation": "Immetti 's', 'n', 'sì' o 'no'."
  },
  {
    "id": "Please enter a number between 1 to {{.Count}}.",
    "translation": "Immetti un numero compreso tra 1 e {{.Count}}."
  },
  {
    "id": "Please enter a valid floating number.",
    "translation": "Immetti un numero decimale valido."
  },
  {
    "id": "Please enter a valid number.",
    "translation": "Immetti un numero valido."
  },
  {
    "id": "Please enter value.",
    "translation": "Immetti un valore."
  },
  {
    "id": "REQUEST:",
    "translation": "RICHIESTA:"
  },
  {
    "id": "RESPONSE:",
    "translation": "RISPOSTA:"
  },
  {
    "id": "Remote server error. Status code: {{.StatusCode}}, error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "Errore server remoto. Codice di stato: {{.StatusCode}}, codice di errore: {{.ErrorCode}}, messaggio: {{.Message}}"
  },
  {
    "id": "Unable to save plugin config: ",
    "translation": "Impossibile salvare la configurazione del plug-in: "
  },
  {
    "id": "Session inactive: ",
    "translation": "Session inactive: "
  }
]
`)

func i18nResourcesAllIt_itJsonBytes() ([]byte, error) {
	return _i18nResourcesAllIt_itJson, nil
}

func i18nResourcesAllIt_itJson() (*asset, error) {
	bytes, err := i18nResourcesAllIt_itJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "i18n/resources/all.it_IT.json", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x88, 0xfd, 0x20, 0xd5, 0x84, 0x7b, 0x16, 0xce, 0x73, 0x4b, 0x14, 0x14, 0x4e, 0x2b, 0x80, 0x71, 0x14, 0xd0, 0x1d, 0xab, 0x10, 0x34, 0xc8, 0x74, 0xa, 0xf2, 0xe, 0x59, 0xf3, 0xdb, 0x9, 0x2e}}
	return a, nil
}

var _i18nResourcesAllJa_jpJson = []byte(`[
  {
    "id": "\nEnter a number",
    "translation": "\n数値を入力してください"
  },
  {
    "id": "An error occurred when creating log file '{{.Path}}':\n{{.Error}}\n\n",
    "translation": "ログ・ファイル '{{.Path}}' を作成中にエラーが発生しました:\n{{.Error}}\n\n"
  },
  {
    "id": "An error occurred while dumping request:\n{{.Error}}\n",
    "translation": "要求のダンプ中にエラーが発生しました:\n{{.Error}}\n"
  },
  {
    "id": "An error occurred while dumping response:\n{{.Error}}\n",
    "translation": "応答のダンプ中にエラーが発生しました:\n{{.Error}}\n"
  },
  {
    "id": "Could not read from input: ",
    "translation": "Could not read from input: "
  },
  {
    "id": "Elapsed:",
    "translation": "経過:"
  },
  {
    "id": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}"
  },
  {
    "id": "FAILED",
    "translation": "失敗"
  },
  {
    "id": "Failed, header could not convert to csv format",
    "translation": "Failed, header could not convert to csv format"
  },
  {
    "id": "Failed, rows could not convert to csv format",
    "translation": "Failed, rows could not convert to csv format"
  },
  {
    "id": "Invalid grant type: ",
    "translation": "Invalid grant type: "
  },
  {
    "id": "Invalid token: ",
    "translation": "トークンが無効です: "
  },
  {
    "id": "OK",
    "translation": "OK"
  },
  {
    "id": "Please enter 'y', 'n', 'yes' or 'no'.",
    "translation": "「y」、「n」、「yes」、または「no」を入力してください。"
  },
  {
    "id": "Please enter a number between 1 to {{.Count}}.",
    "translation": "1 から {{.Count}} までの数値を入力してください。"
  },
  {
    "id": "Please enter a valid floating number.",
    "translation": "有効な浮動小数点数を入力してください。"
  },
  {
    "id": "Please enter a valid number.",
    "translation": "有効な数値を入力してください。"
  },
  {
    "id": "Please enter value.",
    "translation": "値を入力してください。"
  },
  {
    "id": "REQUEST:",
    "translation": "要求:"
  },
  {
    "id": "RESPONSE:",
    "translation": "応答:"
  },
  {
    "id": "Remote server error. Status code: {{.StatusCode}}, error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "リモート・サーバー・エラー。 状況コード: {{.StatusCode}}、エラー・コード: {{.ErrorCode}}、メッセージ: {{.Message}}"
  },
  {
    "id": "Unable to save plugin config: ",
    "translation": "プラグイン構成を保存できません: "
  },
  {
    "id": "Session inactive: ",
    "translation": "Session inactive: "
  }
]
`)

func i18nResourcesAllJa_jpJsonBytes() ([]byte, error) {
	return _i18nResourcesAllJa_jpJson, nil
}

func i18nResourcesAllJa_jpJson() (*asset, error) {
	bytes, err := i18nResourcesAllJa_jpJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "i18n/resources/all.ja_JP.json", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xca, 0x81, 0x11, 0x3f, 0xc4, 0xeb, 0x49, 0x74, 0x94, 0xcd, 0xf2, 0x44, 0x20, 0x46, 0xfa, 0x5a, 0x86, 0x7d, 0xbd, 0xff, 0x6e, 0x6b, 0x0, 0x4f, 0x7a, 0xf3, 0xd0, 0x2d, 0xcc, 0xd6, 0xe6, 0xac}}
	return a, nil
}

var _i18nResourcesAllKo_krJson = []byte(`[
  {
    "id": "\nEnter a number",
    "translation": "\n번호 입력"
  },
  {
    "id": "An error occurred when creating log file '{{.Path}}':\n{{.Error}}\n\n",
    "translation": "'{{.Path}}' 로그 파일을 작성할 때 다음 오류가 발생했습니다. \n{{.Error}}\n\n"
  },
  {
    "id": "An error occurred while dumping request:\n{{.Error}}\n",
    "translation": "요청을 덤프할 때 다음 오류가 발생했습니다. \n{{.Error}}\n"
  },
  {
    "id": "An error occurred while dumping response:\n{{.Error}}\n",
    "translation": "응답을 덤프할 때 다음 오류가 발생했습니다. \n{{.Error}}\n"
  },
  {
    "id": "Could not read from input: ",
    "translation": "Could not read from input: "
  },
  {
    "id": "Elapsed:",
    "translation": "경과 시간:"
  },
  {
    "id": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}"
  },
  {
    "id": "FAILED",
    "translation": "실패"
  },
  {
    "id": "Failed, header could not convert to csv format",
    "translation": "Failed, header could not convert to csv format"
  },
  {
    "id": "Failed, rows could not convert to csv format",
    "translation": "Failed, rows could not convert to csv format"
  },
  {
    "id": "Invalid grant type: ",
    "translation": "Invalid grant type: "
  },
  {
    "id": "Invalid token: ",
    "translation": "올바르지 않은 토큰: "
  },
  {
    "id": "OK",
    "translation": "확인"
  },
  {
    "id": "Please enter 'y', 'n', 'yes' or 'no'.",
    "translation": "'y', 'n', '예' 또는 '아니오'를 입력하십시오."
  },
  {
    "id": "Please enter a number between 1 to {{.Count}}.",
    "translation": "1 - {{.Count}} 사이의 수를 입력하십시오."
  },
  {
    "id": "Please enter a valid floating number.",
    "translation": "올바른 float 수를 입력하십시오."
  },
  {
    "id": "Please enter a valid number.",
    "translation": "올바른 수를 입력하십시오."
  },
  {
    "id": "Please enter value.",
    "translation": "값을 입력하십시오."
  },
  {
    "id": "REQUEST:",
    "translation": "요청:"
  },
  {
    "id": "RESPONSE:",
    "translation": "응답:"
  },
  {
    "id": "Remote server error. Status code: {{.StatusCode}}, error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "원격 서버 오류가 발생했습니다. 상태 코드: {{.StatusCode}}, 오류 코드: {{.ErrorCode}}, 메시지: {{.Message}}"
  },
  {
    "id": "Unable to save plugin config: ",
    "translation": "플러그인 구성을 저장할 수 없음:"
  },
  {
    "id": "Session inactive: ",
    "translation": "Session inactive: "
  }
]
`)

func i18nResourcesAllKo_krJsonBytes() ([]byte, error) {
	return _i18nResourcesAllKo_krJson, nil
}

func i18nResourcesAllKo_krJson() (*asset, error) {
	bytes, err := i18nResourcesAllKo_krJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "i18n/resources/all.ko_KR.json", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xc0, 0xe0, 0x9c, 0xd2, 0x39, 0xfc, 0xe1, 0xba, 0x2, 0x57, 0xde, 0x91, 0x9, 0x72, 0x9, 0xc8, 0x60, 0x10, 0x3c, 0x8b, 0xdf, 0x9f, 0x71, 0xe9, 0xda, 0x70, 0xe6, 0x4, 0xc7, 0xc, 0x8, 0xbf}}
	return a, nil
}

var _i18nResourcesAllPt_brJson = []byte(`[
  {
    "id": "\nEnter a number",
    "translation": "\nInsira um número"
  },
  {
    "id": "An error occurred when creating log file '{{.Path}}':\n{{.Error}}\n\n",
    "translation": "Ocorreu um erro ao criar o arquivo de log '{{.Path}}':\n{{.Error}}\n\n"
  },
  {
    "id": "An error occurred while dumping request:\n{{.Error}}\n",
    "translation": "Ocorreu um erro ao fazer dump da solicitação:\n{{.Error}}\n"
  },
  {
    "id": "An error occurred while dumping response:\n{{.Error}}\n",
    "translation": "Ocorreu um erro ao fazer dump da resposta:\n{{.Error}}\n"
  },
  {
    "id": "Could not read from input: ",
    "translation": "Could not read from input: "
  },
  {
    "id": "Elapsed:",
    "translation": "Decorrido:"
  },
  {
    "id": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}"
  },
  {
    "id": "FAILED",
    "translation": "COM FALHA"
  },
  {
    "id": "Failed, header could not convert to csv format",
    "translation": "Failed, header could not convert to csv format"
  },
  {
    "id": "Failed, rows could not convert to csv format",
    "translation": "Failed, rows could not convert to csv format"
  },
  {
    "id": "Invalid grant type: ",
    "translation": "Invalid grant type: "
  },
  {
    "id": "Invalid token: ",
    "translation": "Token inválido: "
  },
  {
    "id": "OK",
    "translation": "OK"
  },
  {
    "id": "Please enter 'y', 'n', 'yes' or 'no'.",
    "translation": "Insira 'y', 'n', 'yes' ou 'no'."
  },
  {
    "id": "Please enter a number between 1 to {{.Count}}.",
    "translation": "Insira um número entre 1 e {{.Count}}."
  },
  {
    "id": "Please enter a valid floating number.",
    "translation": "Insira um número flutuante válido."
  },
  {
    "id": "Please enter a valid number.",
    "translation": "Digite um número válido."
  },
  {
    "id": "Please enter value.",
    "translation": "Insira um valor."
  },
  {
    "id": "REQUEST:",
    "translation": "SOLICITAÇÃO:"
  },
  {
    "id": "RESPONSE:",
    "translation": "RESPOSTA:"
  },
  {
    "id": "Remote server error. Status code: {{.StatusCode}}, error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "Erro do servidor remoto. Código de status: {{.StatusCode}}, código de erro: {{.ErrorCode}}, mensagem: {{.Message}}"
  },
  {
    "id": "Unable to save plugin config: ",
    "translation": "Não é possível salvar a configuração do plug-in: "
  },
  {
    "id": "Session inactive: ",
    "translation": "Session inactive: "
  }
]
`)

func i18nResourcesAllPt_brJsonBytes() ([]byte, error) {
	return _i18nResourcesAllPt_brJson, nil
}

func i18nResourcesAllPt_brJson() (*asset, error) {
	bytes, err := i18nResourcesAllPt_brJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "i18n/resources/all.pt_BR.json", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xf8, 0x9b, 0x43, 0x5b, 0x29, 0x81, 0x4d, 0x76, 0x96, 0xce, 0x2, 0xda, 0xe8, 0x66, 0xc5, 0xb5, 0xf6, 0x54, 0xf1, 0x9b, 0xca, 0xd6, 0x28, 0x81, 0x45, 0x72, 0x93, 0x37, 0x78, 0x99, 0x59, 0x57}}
	return a, nil
}

var _i18nResourcesAllZh_hansJson = []byte(`[
  {
    "id": "\nEnter a number",
    "translation": "\n请输入数字"
  },
  {
    "id": "An error occurred when creating log file '{{.Path}}':\n{{.Error}}\n\n",
    "translation": "创建日志文件“{{.Path}}”时发生错误：\n{{.Error}}\n\n"
  },
  {
    "id": "An error occurred while dumping request:\n{{.Error}}\n",
    "translation": "转储请求时发生错误：\n{{.Error}}\n"
  },
  {
    "id": "An error occurred while dumping response:\n{{.Error}}\n",
    "translation": "转储响应时发生错误：\n{{.Error}}\n"
  },
  {
    "id": "Could not read from input: ",
    "translation": "Could not read from input: "
  },
  {
    "id": "Elapsed:",
    "translation": "经过时长："
  },
  {
    "id": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}"
  },
  {
    "id": "FAILED",
    "translation": "失败"
  },
  {
    "id": "Failed, header could not convert to csv format",
    "translation": "Failed, header could not convert to csv format"
  },
  {
    "id": "Failed, rows could not convert to csv format",
    "translation": "Failed, rows could not convert to csv format"
  },
  {
    "id": "Invalid grant type: ",
    "translation": "Invalid grant type: "
  },
  {
    "id": "Invalid token: ",
    "translation": "令牌无效："
  },
  {
    "id": "OK",
    "translation": "确定"
  },
  {
    "id": "Please enter 'y', 'n', 'yes' or 'no'.",
    "translation": "请输入“y”、“n”、“yes”或“no”。"
  },
  {
    "id": "Please enter a number between 1 to {{.Count}}.",
    "translation": "请输入 1 到 {{.Count}} 之间的数字。"
  },
  {
    "id": "Please enter a valid floating number.",
    "translation": "请输入有效的浮点数。"
  },
  {
    "id": "Please enter a valid number.",
    "translation": "请输入有效的数字。"
  },
  {
    "id": "Please enter value.",
    "translation": "请输入有效的值。"
  },
  {
    "id": "REQUEST:",
    "translation": "请求: "
  },
  {
    "id": "RESPONSE:",
    "translation": "响应: "
  },
  {
    "id": "Remote server error. Status code: {{.StatusCode}}, error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "远程服务器错误。状态码：{{.StatusCode}}，错误代码：{{.ErrorCode}}，消息：{{.Message}}"
  },
  {
    "id": "Unable to save plugin config: ",
    "translation": "无法保存插件配置："
  },
  {
    "id": "Session inactive: ",
    "translation": "Session inactive: "
  }
]
`)

func i18nResourcesAllZh_hansJsonBytes() ([]byte, error) {
	return _i18nResourcesAllZh_hansJson, nil
}

func i18nResourcesAllZh_hansJson() (*asset, error) {
	bytes, err := i18nResourcesAllZh_hansJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "i18n/resources/all.zh_Hans.json", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x37, 0x4b, 0x89, 0x23, 0x86, 0x1, 0x83, 0xa8, 0xc8, 0x83, 0xc7, 0x55, 0x80, 0xb0, 0xfb, 0x41, 0x2f, 0x48, 0xc1, 0x19, 0x88, 0x66, 0x3b, 0xd0, 0x6f, 0x84, 0x91, 0x8c, 0x70, 0xb, 0x12, 0x87}}
	return a, nil
}

var _i18nResourcesAllZh_hantJson = []byte(`[
  {
    "id": "\nEnter a number",
    "translation": "\n請輸入數字"
  },
  {
    "id": "An error occurred when creating log file '{{.Path}}':\n{{.Error}}\n\n",
    "translation": "建立日誌檔 '{{.Path}}' 時發生錯誤：\n{{.Error}}\n\n"
  },
  {
    "id": "An error occurred while dumping request:\n{{.Error}}\n",
    "translation": "傾出要求時發生錯誤：\n{{.Error}}\n"
  },
  {
    "id": "An error occurred while dumping response:\n{{.Error}}\n",
    "translation": "傾出回應時發生錯誤：\n{{.Error}}\n"
  },
  {
    "id": "Could not read from input: ",
    "translation": "Could not read from input: "
  },
  {
    "id": "Elapsed:",
    "translation": "經歷時間："
  },
  {
    "id": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "External authentication failed. Error code: {{.ErrorCode}}, message: {{.Message}}"
  },
  {
    "id": "FAILED",
    "translation": "失敗"
  },
  {
    "id": "Failed, header could not convert to csv format",
    "translation": "Failed, header could not convert to csv format"
  },
  {
    "id": "Failed, rows could not convert to csv format",
    "translation": "Failed, rows could not convert to csv format"
  },
  {
    "id": "Invalid grant type: ",
    "translation": "Invalid grant type: "
  },
  {
    "id": "Invalid token: ",
    "translation": "無效的記號："
  },
  {
    "id": "OK",
    "translation": "確定"
  },
  {
    "id": "Please enter 'y', 'n', 'yes' or 'no'.",
    "translation": "請輸入 'y'、'n'、'yes' 或 'no'。"
  },
  {
    "id": "Please enter a number between 1 to {{.Count}}.",
    "translation": "請輸入 1 到 {{.Count}} 之間的數字。"
  },
  {
    "id": "Please enter a valid floating number.",
    "translation": "請輸入有效的浮點數。"
  },
  {
    "id": "Please enter a valid number.",
    "translation": "請輸入有效的數字。"
  },
  {
    "id": "Please enter value.",
    "translation": "請輸入值。"
  },
  {
    "id": "REQUEST:",
    "translation": "要求："
  },
  {
    "id": "RESPONSE:",
    "translation": "回應："
  },
  {
    "id": "Remote server error. Status code: {{.StatusCode}}, error code: {{.ErrorCode}}, message: {{.Message}}",
    "translation": "遠端伺服器錯誤。狀態碼：{{.StatusCode}}，錯誤碼：{{.ErrorCode}}，訊息：{{.Message}}"
  },
  {
    "id": "Unable to save plugin config: ",
    "translation": "無法儲存外掛程式配置："
  },
  {
    "id": "Session inactive: ",
    "translation": "Session inactive: "
  }
]
`)

func i18nResourcesAllZh_hantJsonBytes() ([]byte, error) {
	return _i18nResourcesAllZh_hantJson, nil
}

func i18nResourcesAllZh_hantJson() (*asset, error) {
	bytes, err := i18nResourcesAllZh_hantJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "i18n/resources/all.zh_Hant.json", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x62, 0xa8, 0x1, 0xf0, 0x6a, 0xd5, 0x31, 0xaf, 0x2b, 0x40, 0xf0, 0xc0, 0x39, 0x8, 0xda, 0x1d, 0x66, 0xd0, 0x11, 0xcc, 0xaa, 0x7, 0xbd, 0x45, 0x3f, 0x9b, 0x8d, 0xc5, 0x50, 0x5f, 0xf0, 0xfa}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"i18n/resources/all.de_DE.json":   i18nResourcesAllDe_deJson,
	"i18n/resources/all.en_US.json":   i18nResourcesAllEn_usJson,
	"i18n/resources/all.es_ES.json":   i18nResourcesAllEs_esJson,
	"i18n/resources/all.fr_FR.json":   i18nResourcesAllFr_frJson,
	"i18n/resources/all.it_IT.json":   i18nResourcesAllIt_itJson,
	"i18n/resources/all.ja_JP.json":   i18nResourcesAllJa_jpJson,
	"i18n/resources/all.ko_KR.json":   i18nResourcesAllKo_krJson,
	"i18n/resources/all.pt_BR.json":   i18nResourcesAllPt_brJson,
	"i18n/resources/all.zh_Hans.json": i18nResourcesAllZh_hansJson,
	"i18n/resources/all.zh_Hant.json": i18nResourcesAllZh_hantJson,
}

// AssetDebug is true if the assets were built with the debug flag enabled.
const AssetDebug = false

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//
//	data/
//	  foo.txt
//	  img/
//	    a.png
//	    b.png
//
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"i18n": {nil, map[string]*bintree{
		"resources": {nil, map[string]*bintree{
			"all.de_DE.json":   {i18nResourcesAllDe_deJson, map[string]*bintree{}},
			"all.en_US.json":   {i18nResourcesAllEn_usJson, map[string]*bintree{}},
			"all.es_ES.json":   {i18nResourcesAllEs_esJson, map[string]*bintree{}},
			"all.fr_FR.json":   {i18nResourcesAllFr_frJson, map[string]*bintree{}},
			"all.it_IT.json":   {i18nResourcesAllIt_itJson, map[string]*bintree{}},
			"all.ja_JP.json":   {i18nResourcesAllJa_jpJson, map[string]*bintree{}},
			"all.ko_KR.json":   {i18nResourcesAllKo_krJson, map[string]*bintree{}},
			"all.pt_BR.json":   {i18nResourcesAllPt_brJson, map[string]*bintree{}},
			"all.zh_Hans.json": {i18nResourcesAllZh_hansJson, map[string]*bintree{}},
			"all.zh_Hant.json": {i18nResourcesAllZh_hantJson, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
