name: ci

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Display Go version
        run: go version
      - name: Build Dependencies
        run: go mod tidy && go mod vendor
      - name: Run Tests
        run: go test -v -count=1 ./...
